import { MD3LightTheme } from 'react-native-paper';

export const semanticColors = {
  screenBackground: '#F4F0E8',
  cardBackground: '#FCF8F1',
  cardBorder: '#A49887',
  mutedText: '#6D6457',
  chartGrid: '#D9D0C2',
  chartAxis: '#8F8578',
  positive: '#2F7A5A',
  negative: '#C24E3A',
  warning: '#BC8C1D',
  accent: '#0E5A8A',
  ink: '#1F1A14',
  scoreLow: '#C24E3A',
  scoreMedium: '#BC8C1D',
  scoreHigh: '#2F7A5A',
  income: '#2F7A5A',
  expenses: '#C24E3A',
  risk: '#B33D2E',
  neutral: '#0E5A8A',
  muted: '#6D6457',
} as const;

export const appTheme = {
  ...MD3LightTheme,
  roundness: 5,
  colors: {
    ...MD3LightTheme.colors,
    primary: semanticColors.accent,
    onPrimary: '#FFFFFF',
    primaryContainer: '#CFE7F5',
    onPrimaryContainer: '#052B45',
    secondary: '#7E6A35',
    secondaryContainer: '#F2E6BE',
    tertiary: semanticColors.positive,
    tertiaryContainer: '#CDEBDE',
    background: semanticColors.screenBackground,
    onBackground: semanticColors.ink,
    surface: semanticColors.cardBackground,
    onSurface: semanticColors.ink,
    surfaceVariant: '#E5DED2',
    onSurfaceVariant: '#4F4639',
    outline: semanticColors.cardBorder,
    error: semanticColors.risk,
    errorContainer: '#F9D9D4',
  },
};
